healthdemo/hc/urls.py
from django.contrib import admin
from django.urls import include, path

from hc.accounts import views as accounts_views

urlpatterns = [
    path("admin/login/", accounts_views.login),
    path("admin/", admin.site.urls),
    path("accounts/", include("hc.accounts.urls")),
    path("projects/add/", accounts_views.add_project, name="hc-add-project"),
    path(
        "projects/<uuid:code>/settings/",
        accounts_views.project,
        name="hc-project-settings",
    ),
    path(
        "projects/<uuid:code>/remove/",
        accounts_views.remove_project,
        name="hc-remove-project",
    ),
    path("", include("hc.api.urls")),
    path("", include("hc.front.urls")),
    path("", include("hc.payments.urls")),
]

healthdemo/hc/front/forms.py
from datetime import timedelta as td
import json
import re
from urllib.parse import quote, urlencode

from django import forms
from django.conf import settings
from django.core.validators import RegexValidator
from hc.front.validators import (
    CronExpressionValidator,
    TimezoneValidator,
    WebhookValidator,
)
import requests


class NameTagsForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    tags = forms.CharField(max_length=500, required=False)
    desc = forms.CharField(required=False)

    def clean_tags(self):
        result = []

        for part in self.cleaned_data["tags"].split(" "):
            part = part.strip()
            if part != "":
                result.append(part)

        return " ".join(result)


class EmailSettingsForm(forms.Form):
    subject = forms.CharField(max_length=100)


class TimeoutForm(forms.Form):
    timeout = forms.IntegerField(min_value=60, max_value=2592000)
    grace = forms.IntegerField(min_value=60, max_value=2592000)

    def clean_timeout(self):
        return td(seconds=self.cleaned_data["timeout"])

    def clean_grace(self):
        return td(seconds=self.cleaned_data["grace"])


class CronForm(forms.Form):
    schedule = forms.CharField(max_length=100, validators=[CronExpressionValidator()])
    tz = forms.CharField(max_length=36, validators=[TimezoneValidator()])
    grace = forms.IntegerField(min_value=1, max_value=43200)


class AddOpsGenieForm(forms.Form):
    error_css_class = "has-error"
    value = forms.CharField(max_length=40)


class AddEmailForm(forms.Form):
    error_css_class = "has-error"
    value = forms.EmailField(max_length=100)
    down = forms.BooleanField(required=False, initial=True)
    up = forms.BooleanField(required=False, initial=True)


class AddUrlForm(forms.Form):
    error_css_class = "has-error"
    value = forms.URLField(max_length=1000, validators=[WebhookValidator()])


_valid_header_name = re.compile(r"\A[^:\s][^:\r\n]*\Z").match


class AddWebhookForm(forms.Form):
    error_css_class = "has-error"

    url_down = forms.URLField(
        max_length=1000, required=False, validators=[WebhookValidator()]
    )

    url_up = forms.URLField(
        max_length=1000, required=False, validators=[WebhookValidator()]
    )

    post_data = forms.CharField(max_length=1000, required=False)

    def __init__(self, *args, **kwargs):
        super(AddWebhookForm, self).__init__(*args, **kwargs)

        self.invalid_header_names = set()
        self.headers = {}
        if "header_key[]" in self.data and "header_value[]" in self.data:
            keys = self.data.getlist("header_key[]")
            values = self.data.getlist("header_value[]")
            for key, value in zip(keys, values):
                if not key:
                    continue

                if not _valid_header_name(key):
                    self.invalid_header_names.add(key)

                self.headers[key] = value

    def clean(self):
        if self.invalid_header_names:
            raise forms.ValidationError("Invalid header names")

        return self.cleaned_data

    def get_value(self):
        val = dict(self.cleaned_data)
        val["headers"] = self.headers
        return json.dumps(val, sort_keys=True)


phone_validator = RegexValidator(
    regex="^\+\d{5,15}$", message="Invalid phone number format."
)


class AddSmsForm(forms.Form):
    error_css_class = "has-error"
    label = forms.CharField(max_length=100, required=False)
    value = forms.CharField(max_length=16, validators=[phone_validator])


class ChannelNameForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)


class AddMatrixForm(forms.Form):
    error_css_class = "has-error"
    alias = forms.CharField(max_length=40)

    def clean_alias(self):
        v = self.cleaned_data["alias"]

        # validate it by trying to join
        url = settings.MATRIX_HOMESERVER
        url += "/_matrix/client/r0/join/%s?" % quote(v)
        url += urlencode({"access_token": settings.MATRIX_ACCESS_TOKEN})
        doc = requests.post(url, {}).json()
        if "error" in doc:
            raise forms.ValidationError("Response from Matrix: %s" % doc["error"])

        self.cleaned_data["room_id"] = doc["room_id"]

        return v

healthdemo/templates/integrations/add_discord.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add Discord - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>Discord</h1>

    <div class="jumbotron">
        <p>
            With this integration, {% site_name %} will send
            a notification to a <a href="http://discord.com/">Discord</a>
            channel when a check
            goes <strong>up</strong> or <strong>down</strong>.
        </p>

        <form method="post" class="text-center">
            {% csrf_token %}
            <a href="{{ authorize_url }}" class="btn btn-lg btn-default">
                <img class="ai-icon" src="{% static 'img/integrations/discord.png' %}" alt="Discord" />
                Connect Discord
            </a>
        </form>
    </div>
</div>
</div>
{% endblock %}

healthdemo/templates/integrations/add_pagerteam.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add Pager Team - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
  <div class="col-sm-12">
      <h1>Pager Team</h1>

      <p>You can integrate <a href="https://pagerteam.com">Pager Team</a>
      with {% site_name %} to alert your on-call rotation whenever a check goes down.</p>

      <h2>Setup Guide</h2>

      <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                Log into your Pager Team account, select the rotation you wish to add this integration to. Click the <strong>Copy Webhook</strong> button.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Click create integration button"
                src="{% static 'img/integrations/setup_pagerteam_1.png' %}">
        </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no">2</span>
              <p>
                Paste the <strong>Webhook URL</strong> below. Save the integration, and you are done!
              </p>
          </div>
      </div>

      <h2>Integration Settings</h2>

      <form method="post" class="form-horizontal" action="{% url 'hc-add-pagerteam' %}">
          {% csrf_token %}
          <div class="form-group {{ form.value.css_classes }}">
              <label for="post-url" class="col-sm-2 control-label">URL</label>
              <div class="col-sm-10">
                  <input
                      id="post-url"
                      type="text"
                      class="form-control"
                      name="value"
                      placeholder="https://"
                      value="{{ form.value.value|default:"" }}">

                  {% if form.value.errors %}
                  <div class="help-block">
                      {{ form.value.errors|join:"" }}
                  </div>
                  {% endif %}
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">Save Integration</button>
              </div>
          </div>
      </form>
  </div>
</div>
{% endblock %}

healthdemo/templates/integrations/add_pagertree.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add PagerTree - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
  <div class="col-sm-12">
      <h1>PagerTree</h1>

      <p>If your team uses <a href="https://pagertree.com">PagerTree</a>,
      you can set up {% site_name %} to create a PagerTree incident when
      a check goes down, and resolve it when a check goes back up.</p>

      <h2>Setup Guide</h2>

      <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                Log into your PagerTree account, click the <strong>Integrations</strong> tab.
                Then click the <strong>Create Integration</strong> button.
            </p>
        </div>
        <div class="col-sm-6">
            <div class="marker-wrap">
                <span style="left: 89%; top: 19%;" class="marker"></span>
                <img
                    class="ai-guide-screenshot"
                    alt="Click create integration button"
                    src="{% static 'img/integrations/setup_pagertree_1.png' %}" />
            </div>
        </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no">2</span>
              <p>
                  In the Create Integration Form, fill out the details with appropriate values, but most importantly make sure the <strong>Integration Type</strong> is set to <strong>Healthchecks.io</strong>. Then click the <strong>Create</strong> button.
              </p>
          </div>
          <div class="col-sm-6">
              <img
                  class="ai-guide-screenshot"
                  alt="Create Healthchecks.io integration with details"
                  src="{% static 'img/integrations/setup_pagertree_2.png' %}">
          </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no">3</span>
              <p>
                Copy the <strong>Endpoint address</strong> and paste it
                in the form below.
                Save the integration, and you are done!
              </p>
          </div>
          <div class="col-sm-6">
            <div class="marker-wrap">
                <span style="left: 32%; top: 59%;" class="marker"></span>

                  <img
                      class="ai-guide-screenshot"
                      alt="Copy the Webhook URL"
                      src="{% static 'img/integrations/setup_pagertree_3.png' %}">
            </div>
          </div>
      </div>

      <h2>Integration Settings</h2>

      <form method="post" class="form-horizontal" action="{% url 'hc-add-pagertree' %}">
          {% csrf_token %}
          <div class="form-group {{ form.value.css_classes }}">
              <label for="post-url" class="col-sm-2 control-label">Endpoint</label>
              <div class="col-sm-10">
                  <input
                      id="post-url"
                      type="text"
                      class="form-control"
                      name="value"
                      placeholder="https://"
                      value="{{ form.value.value|default:"" }}">

                  {% if form.value.errors %}
                  <div class="help-block">
                      {{ form.value.errors|join:"" }}
                  </div>
                  {% endif %}
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">Save Integration</button>
              </div>
          </div>
      </form>
  </div>
</div>
{% endblock %}

healthdemo/templates/integrations/add_slack.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add Slack - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">

    {% if slack_client_id %}
    <div class="jumbotron">
        {% if request.user.is_authenticated %}
        <p>If your team uses <a href="https://slack.com/">Slack</a>, you can set
        up {% site_name %} to post status updates directly to an appropriate
        Slack channel.</p>

        <div class="text-center">
        <a href="https://slack.com/oauth/authorize?scope=incoming-webhook&client_id={{ slack_client_id }}&state={{ state }}">
            <img
                alt="Add to Slack"
                src="{% static 'img/integrations/add_to_slack.png' %}"
                srcset="{% static 'img/integrations/add_to_slack.png' %} 1x, {% static 'img/integrations/add_to_slack@2x.png' %} 2x" />
        </a>
        </div>

        {% else %}
        <p>
        {% site_name %} is a <strong>free</strong> and
        <a href="https://github.com/healthchecks/healthchecks">open source</a>
        service for monitoring your cron jobs, background processes and
        scheduled tasks. Before adding Slack integration, please log into
        {% site_name %}:</p>

        <div class="text-center">
            <a href="{% url 'hc-login' %}?next={% url 'hc-add-slack' %}"
               class="btn btn-primary btn-lg">Sign In</a>
        </div>
        {% endif %}
    </div>

    <h2>Setup Guide</h2>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                After {% if request.user.is_authenticated %}{% else %}signing in and{% endif %}
                clicking on "Add to Slack", you should
                be on a page that says "{% site_name %} would like access to
                your Slack team". Select the team you want to add the
                {% site_name %} integration app to.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_1.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">2</span>
            <p>
                You should now be on a page that says "{% site_name %} would
                like access to <i>TEAM NAME</i>". Select the channel you want to
                post {% site_name %} notifications to.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_2.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">3</span>
            <p>
                That is all! You will now be redirected back to
                "Integrations" page on {% site_name %} and see
                the new integration!
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_btn_3.png' %}">
        </div>
    </div>
    {% else %}
    <h1>Slack</h1>

    <p>If your team uses <a href="https://slack.com/">Slack</a>, you can set
    up {% site_name %} to post status updates directly to an appropriate
    Slack channel.</p>

    <h2>Setup Guide</h2>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            Log into your Slack account and
            pick an appropriate Slack channel. From the dropdown next to
            channel's name, pick <strong>Add a service integration...</strong>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_1.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">2</span>
            From the list of available integrations, select
            <strong>Incoming WebHooks</strong>, and click on
            <strong>Add Incoming WebHooks Integration</strong>.
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">3</span>
            <p>Copy the displayed <strong>WebHook URL</strong> and paste it down below.</p>
            <p>Save the integration, and it's done!</p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_slack_2.png' %}">
        </div>
    </div>

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-slack' %}">
        {% csrf_token %}
        <div class="form-group {{ form.value.css_classes }}">
            <label for="callback-url" class="col-sm-2 control-label">
                Callback URL
            </label>
            <div class="col-sm-10">
                <input
                    id="callback-url"
                    type="text"
                    class="form-control"
                    name="value"
                    placeholder="https://"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>
</div>
{% endblock %}

healthdemo/templates/integrations/add_sms.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Notification Channels - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>SMS</h1>

    <p>
        Get a SMS message to the specified phone number when a
        check goes down.
    </p>

    {% if show_pricing and profile.sms_limit == 0 %}
    <p class="alert alert-info">
        <strong>Paid plan required.</strong>
        SMS messaging is not available on the free plan–sending the messages
        cost too much! Please upgrade to a
        <a href="{% url 'hc-billing' %}">paid plan</a> to enable SMS messaging.
    </p>
    {% endif %}

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-sms' %}">
        {% csrf_token %}
        <div class="form-group {{ form.label.css_classes }}">
            <label for="id_label" class="col-sm-2 control-label">Label</label>
            <div class="col-sm-6">
                <input
                    id="id_label"
                    type="text"
                    class="form-control"
                    name="label"
                    placeholder="Alice's Phone"
                    value="{{ form.label.value|default:"" }}">

                {% if form.label.errors %}
                <div class="help-block">
                    {{ form.label.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Optional. If you add multiple phone numbers,
                    the labels will help you tell them apart.
                </span>
                {% endif %}
            </div>
        </div>
        <div class="form-group {{ form.value.css_classes }}">
            <label for="id_number" class="col-sm-2 control-label">Phone Number</label>
            <div class="col-sm-3">
                <input
                    id="id_number"
                    type="tel"
                    class="form-control"
                    name="value"
                    placeholder="+1234567890"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Make sure the phone number starts with "+" and  has the
                    country code.
                </span>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

healthdemo/templates/integrations/add_victorops.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add VictorOps - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>VictorOps</h1>

    <p><a href="https://victorops.com/">VictorOps</a> is
    another incident management system similar to PagerDuty.
    If you use or plan on using VictorOps, you can can integrate it
    with your {% site_name %} account in few simple steps.</p>

    <h2>Setup Guide</h2>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                Log into your VictorOps account,
                go to <strong>Settings > Schedules</strong>,
                and find or create the Team Schedule you
                would like to use for {% site_name %} alerts.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_victorops_1.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">2</span>
            <p>
                Go to <strong>Settings &gt; Integrations</strong> and scroll
                to the bottom of the page. Choose an existing
                <strong>Routing Key</strong> or
                add a new one, and make note of it.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_victorops_2.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">3</span>
            In the right hand side of
            <strong>Settings &gt; Integrations</strong> page,
            select <strong>REST Endpoint</strong>, and click on
            <strong>Enable Integration</strong>.
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_victorops_3.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">4</span>
            <p>Paste the <strong>Post URL</strong> from step 3 in the field
            below, being careful to replace <strong>$routing_key</strong>
            with your actual Routing Key from step 2. Save the integration,
            and it's done!</p>
        </div>
    </div>

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-victorops' %}">
        {% csrf_token %}
        <div class="form-group {{ form.value.css_classes }}">
            <label for="post-url" class="col-sm-2 control-label">Post URL</label>
            <div class="col-sm-10">
                <input
                    id="post-url"
                    type="text"
                    class="form-control"
                    name="value"
                    placeholder="https://"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

healthdemo/templates/integrations/matrix_description.html
{% load humanize %}
{% if check.status == "down" %}
    {{ check.name_then_code }} is DOWN. Last ping was {{ check.last_ping|naturaltime }}.
{% else %}
    {{ check.name_then_code }} is now UP.
{% endif %}

healthdemo/templates/integrations/opsgenie_description.html
{% load hc_extras humanize %}
The check "{{ check.name_then_code }}" is DOWN.
{% if check.kind == "simple" %}Expecting to receive a ping every {{ check.timeout|hc_duration }}.{% endif %}
Last ping was {{ check.last_ping|naturaltime }}.

healthdemo/templates/integrations/opsgenie_note.html
{% load hc_extras humanize %}

{% if check.kind == "simple" %}Expecting to receive a ping every {{ check.timeout|hc_duration }}.{% endif %}
Last ping was {{ check.last_ping|naturaltime }}.

healthdemo/templates/integrations/pushbullet_message.html
{% load humanize %}

{% if check.status == "down" %}
The check "{{ check.name_then_code }}" is DOWN. Last ping was {{ check.last_ping|naturaltime }}
{% else %}
The check "{{ check.name_then_code }}" received a ping and is now UP.
{% endif %}

healthdemo/templates/integrations/sms_message.html
{% load humanize %}{{ site_name }}: The check "{{ check.name_then_code }}" is DOWN. Last ping was {{ check.last_ping|naturaltime }}.

healthdemo/templates/integrations/trello_desc.html
{% load hc_extras humanize %}
{{ check.desc|safe }}

{% if check.kind == "simple" %}
**Period:** {{ check.timeout|hc_duration }}
{% endif %}

{% if check.kind == "cron" %}
**Schedule:** {{ check.schedule|escapejs }}
{% endif %}

**Last Ping:** {{ check.last_ping|naturaltime }}

[Full Details @ {% site_name %}]({{ check.details_url }})

healthdemo/templates/integrations/victorops_description.html
{% load humanize %}
{% if check.status == "down" %}
    {{ check.name_then_code }} is DOWN.
    Last ping was {{ check.last_ping|naturaltime }}.
{% else %}
    {{ check.name_then_code }} received a ping and is now UP
{% endif %}

healthdemo/templates/integrations/zendesk_description.html
{% load humanize %}
{% if check.status == "down" %}
    {{ check.name_then_code }} is down.
    Last ping was {{ check.last_ping|naturaltime }}.
    Details: {{ check.details_url }}
{% else %}
    {{ check.name_then_code }} received a ping and is now UP
{% endif %}