healthdemo/hc/front/urls.py
from django.urls import include, path

from hc.front import views

check_urls = [
    path("name/", views.update_name, name="hc-update-name"),
    path("details/", views.details, name="hc-details"),
    path("email_settings/", views.email_settings, name="hc-email-settings"),
    path("timeout/", views.update_timeout, name="hc-update-timeout"),
    path("pause/", views.pause, name="hc-pause"),
    path("remove/", views.remove_check, name="hc-remove-check"),
    path("log/", views.log, name="hc-log"),
    path("status/", views.status_single),
    path("last_ping/", views.ping_details, name="hc-last-ping"),
    path("transfer/", views.transfer, name="hc-transfer"),
    path(
        "channels/<uuid:channel_code>/enabled",
        views.switch_channel,
        name="hc-switch-channel",
    ),
    path("pings/<int:n>/", views.ping_details, name="hc-ping-details"),
]

channel_urls = [
    path("", views.channels, name="hc-channels"),
    path("add_email/", views.add_email, name="hc-add-email"),
    path("add_webhook/", views.add_webhook, name="hc-add-webhook"),
    path("add_pd/", views.add_pd, name="hc-add-pd"),
    path("add_pd/<str:state>/", views.add_pd, name="hc-add-pd-state"),
    path("add_pagertree/", views.add_pagertree, name="hc-add-pagertree"),
    path("add_pagerteam/", views.add_pagerteam, name="hc-add-pagerteam"),
    path("add_slack/", views.add_slack, name="hc-add-slack"),
    path("add_slack_btn/", views.add_slack_btn, name="hc-add-slack-btn"),
    path("add_pushbullet/", views.add_pushbullet, name="hc-add-pushbullet"),
    path("add_discord/", views.add_discord, name="hc-add-discord"),
    path("add_pushover/", views.add_pushover, name="hc-add-pushover"),
    path("add_opsgenie/", views.add_opsgenie, name="hc-add-opsgenie"),
    path("add_victorops/", views.add_victorops, name="hc-add-victorops"),
    path("telegram/bot/", views.telegram_bot, name="hc-telegram-webhook"),
    path("add_telegram/", views.add_telegram, name="hc-add-telegram"),
    path("add_sms/", views.add_sms, name="hc-add-sms"),
    path("add_trello/", views.add_trello, name="hc-add-trello"),
    path("add_trello/settings/", views.trello_settings, name="hc-trello-settings"),
    path("add_matrix/", views.add_matrix, name="hc-add-matrix"),
    path("<uuid:code>/checks/", views.channel_checks, name="hc-channel-checks"),
    path("<uuid:code>/name/", views.update_channel_name, name="hc-channel-name"),
    path("<uuid:code>/test/", views.send_test_notification, name="hc-channel-test"),
    path("<uuid:code>/remove/", views.remove_channel, name="hc-remove-channel"),
    path(
        "<uuid:code>/verify/<slug:token>/", views.verify_email, name="hc-verify-email"
    ),
    path(
        "<uuid:code>/unsub/<slug:token>/",
        views.unsubscribe_email,
        name="hc-unsubscribe-alerts",
    ),
]

urlpatterns = [
    path("", views.index, name="hc-index"),
    path("projects/<uuid:code>/checks/", views.my_checks, name="hc-checks"),
    path("projects/<uuid:code>/badges/", views.badges, name="hc-badges"),
    path("projects/<uuid:code>/checks/add/", views.add_check, name="hc-add-check"),
    path("checks/cron_preview/", views.cron_preview),
    path("projects/<uuid:code>/checks/status/", views.status, name="hc-status"),
    path("checks/<uuid:code>/", include(check_urls)),
    path("integrations/", include(channel_urls)),
    path("docs/", views.docs, name="hc-docs"),
    path("docs/api/", views.docs_api, name="hc-docs-api"),
    path("docs/cron/", views.docs_cron, name="hc-docs-cron"),
    path("docs/resources/", views.docs_resources, name="hc-docs-resources"),
]

healthdemo/hc/urls.py
from django.contrib import admin
from django.urls import include, path

from hc.accounts import views as accounts_views

urlpatterns = [
    path("admin/login/", accounts_views.login),
    path("admin/", admin.site.urls),
    path("accounts/", include("hc.accounts.urls")),
    path("projects/add/", accounts_views.add_project, name="hc-add-project"),
    path(
        "projects/<uuid:code>/settings/",
        accounts_views.project,
        name="hc-project-settings",
    ),
    path(
        "projects/<uuid:code>/remove/",
        accounts_views.remove_project,
        name="hc-remove-project",
    ),
    path("", include("hc.api.urls")),
    path("", include("hc.front.urls")),
    path("", include("hc.payments.urls")),
]

healthdemo/hc/api/models.py
# coding: utf-8

import hashlib
import json
import uuid
from datetime import datetime, timedelta as td

from croniter import croniter
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from hc.accounts.models import Project
from hc.api import transports
from hc.lib import emails
import pytz

STATUSES = (("up", "Up"), ("down", "Down"), ("new", "New"), ("paused", "Paused"))
DEFAULT_TIMEOUT = td(days=1)
DEFAULT_GRACE = td(hours=1)
NEVER = datetime(3000, 1, 1, tzinfo=pytz.UTC)
CHECK_KINDS = (("simple", "Simple"), ("cron", "Cron"))

CHANNEL_KINDS = (
    ("email", "Email"),
    ("webhook", "Webhook"),
    ("hipchat", "HipChat"),
    ("slack", "Slack"),
    ("pd", "PagerDuty"),
    ("pagertree", "PagerTree"),
    ("pagerteam", "Pager Team"),
    ("po", "Pushover"),
    ("pushbullet", "Pushbullet"),
    ("opsgenie", "OpsGenie"),
    ("victorops", "VictorOps"),
    ("discord", "Discord"),
    ("telegram", "Telegram"),
    ("sms", "SMS"),
    ("zendesk", "Zendesk"),
    ("trello", "Trello"),
    ("matrix", "Matrix"),
)

PO_PRIORITIES = {-2: "lowest", -1: "low", 0: "normal", 1: "high", 2: "emergency"}


def isostring(dt):
    """Convert the datetime to ISO 8601 format with no microseconds. """

    if dt:
        return dt.replace(microsecond=0).isoformat()


class Check(models.Model):
    name = models.CharField(max_length=100, blank=True)
    tags = models.CharField(max_length=500, blank=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    desc = models.TextField(blank=True)
    project = models.ForeignKey(Project, models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    kind = models.CharField(max_length=10, default="simple", choices=CHECK_KINDS)
    timeout = models.DurationField(default=DEFAULT_TIMEOUT)
    grace = models.DurationField(default=DEFAULT_GRACE)
    schedule = models.CharField(max_length=100, default="* * * * *")
    tz = models.CharField(max_length=36, default="UTC")
    subject = models.CharField(max_length=100, blank=True)
    n_pings = models.IntegerField(default=0)
    last_ping = models.DateTimeField(null=True, blank=True)
    last_start = models.DateTimeField(null=True, blank=True)
    last_ping_was_fail = models.NullBooleanField(default=False)
    has_confirmation_link = models.BooleanField(default=False)
    alert_after = models.DateTimeField(null=True, blank=True, editable=False)
    status = models.CharField(max_length=6, choices=STATUSES, default="new")

    def __str__(self):
        return "%s (%d)" % (self.name or self.code, self.id)

    def name_then_code(self):
        if self.name:
            return self.name

        return str(self.code)

    def url(self):
        return settings.PING_ENDPOINT + str(self.code)

    def details_url(self):
        return settings.SITE_ROOT + reverse("hc-details", args=[self.code])

    def email(self):
        return "%s@%s" % (self.code, settings.PING_EMAIL_DOMAIN)

    def get_grace_start(self):
        """ Return the datetime when the grace period starts.

        If the check is currently new, paused or down, return None.

        """

        # NEVER is a constant sentinel value (year 3000).
        # Using None instead would make the logic clunky.
        result = NEVER

        if self.kind == "simple" and self.status == "up":
            result = self.last_ping + self.timeout
        elif self.kind == "cron" and self.status == "up":
            # The complex case, next ping is expected based on cron schedule.
            # Don't convert to naive datetimes (and so avoid ambiguities around
            # DST transitions). Croniter will handle the timezone-aware datetimes.

            zone = pytz.timezone(self.tz)
            last_local = timezone.localtime(self.last_ping, zone)
            it = croniter(self.schedule, last_local)
            result = it.next(datetime)

        if self.last_start and self.status != "down":
            result = min(result, self.last_start)

        if result != NEVER:
            return result

    def going_down_after(self):
        """ Return the datetime when the check goes down.

        If the check is new or paused, and not currently running, return None.
        If the check is already down, also return None.

        """

        grace_start = self.get_grace_start()
        if grace_start is not None:
            return grace_start + self.grace

    def get_status(self, now=None, with_started=True):
        """ Return current status for display. """

        if now is None:
            now = timezone.now()

        if self.last_start:
            if now >= self.last_start + self.grace:
                return "down"
            elif with_started:
                return "started"

        if self.status in ("new", "paused", "down"):
            return self.status

        grace_start = self.get_grace_start()
        grace_end = grace_start + self.grace
        if now >= grace_end:
            return "down"

        if now >= grace_start:
            return "grace"

        return "up"

    def assign_all_channels(self):
        channels = Channel.objects.filter(project=self.project)
        self.channel_set.set(channels)

    def tags_list(self):
        return [t.strip() for t in self.tags.split(" ") if t.strip()]

    def matches_tag_set(self, tag_set):
        return tag_set.issubset(self.tags_list())

    def to_dict(self):
        update_rel_url = reverse("hc-api-update", args=[self.code])
        pause_rel_url = reverse("hc-api-pause", args=[self.code])
        channel_codes = [str(ch.code) for ch in self.channel_set.all()]

        result = {
            "name": self.name,
            "ping_url": self.url(),
            "update_url": settings.SITE_ROOT + update_rel_url,
            "pause_url": settings.SITE_ROOT + pause_rel_url,
            "tags": self.tags,
            "grace": int(self.grace.total_seconds()),
            "n_pings": self.n_pings,
            "status": self.get_status(),
            "channels": ",".join(sorted(channel_codes)),
            "last_ping": isostring(self.last_ping),
            "next_ping": isostring(self.get_grace_start()),
            "desc": self.desc,
        }

        if self.kind == "simple":
            result["timeout"] = int(self.timeout.total_seconds())
        elif self.kind == "cron":
            result["schedule"] = self.schedule
            result["tz"] = self.tz

        return result

    def ping(self, remote_addr, scheme, method, ua, body, action):
        if action == "start":
            self.last_start = timezone.now()
            # Don't update "last_ping" field.
        elif action == "ign":
            pass
        else:
            self.last_start = None
            self.last_ping = timezone.now()

            new_status = "down" if action == "fail" else "up"
            if self.status != new_status:
                flip = Flip(owner=self)
                flip.created = self.last_ping
                flip.old_status = self.status
                flip.new_status = new_status
                flip.save()

                self.status = new_status

        self.alert_after = self.going_down_after()
        self.n_pings = models.F("n_pings") + 1
        self.has_confirmation_link = "confirm" in str(body).lower()
        self.save()
        self.refresh_from_db()

        ping = Ping(owner=self)
        ping.n = self.n_pings
        if action in ("start", "fail", "ign"):
            ping.kind = action

        ping.remote_addr = remote_addr
        ping.scheme = scheme
        ping.method = method
        # If User-Agent is longer than 200 characters, truncate it:
        ping.ua = ua[:200]
        ping.body = body[:10000]
        ping.save()


class Ping(models.Model):
    id = models.BigAutoField(primary_key=True)
    n = models.IntegerField(null=True)
    owner = models.ForeignKey(Check, models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    kind = models.CharField(max_length=6, blank=True, null=True)
    scheme = models.CharField(max_length=10, default="http")
    remote_addr = models.GenericIPAddressField(blank=True, null=True)
    method = models.CharField(max_length=10, blank=True)
    ua = models.CharField(max_length=200, blank=True)
    body = models.CharField(max_length=10000, blank=True, null=True)


class Channel(models.Model):
    name = models.CharField(max_length=100, blank=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    project = models.ForeignKey(Project, models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    kind = models.CharField(max_length=20, choices=CHANNEL_KINDS)
    value = models.TextField(blank=True)
    email_verified = models.BooleanField(default=False)
    checks = models.ManyToManyField(Check)

    def __str__(self):
        if self.name:
            return self.name
        if self.kind == "email":
            return "Email to %s" % self.email_value
        elif self.kind == "sms":
            return "SMS to %s" % self.sms_number
        elif self.kind == "slack":
            return "Slack %s" % self.slack_channel
        elif self.kind == "telegram":
            return "Telegram %s" % self.telegram_name

        return self.get_kind_display()

    def to_dict(self):
        return {"id": str(self.code), "name": self.name, "kind": self.kind}

    def assign_all_checks(self):
        checks = Check.objects.filter(project=self.project)
        self.checks.add(*checks)

    def make_token(self):
        seed = "%s%s" % (self.code, settings.SECRET_KEY)
        seed = seed.encode()
        return hashlib.sha1(seed).hexdigest()

    def send_verify_link(self):
        args = [self.code, self.make_token()]
        verify_link = reverse("hc-verify-email", args=args)
        verify_link = settings.SITE_ROOT + verify_link
        emails.verify_email(self.email_value, {"verify_link": verify_link})

healthdemo/hc/front/models.py
from django.db import models

# Create your models here.

healthdemo/templates/front/docs.html
{% extends "front/base_docs.html" %}
{% load compress static hc_extras %}

{% block title %}Documentation - {% site_name %}{% endblock %}
{% block description %}
    <meta name="description" content="Monitor any service that can make a HTTP request or send an email: cron jobs, Bash scripts, Python, Ruby, Node, PHP, JS, ...">
{% endblock %}
{% block keywords %}
    <meta name="keywords" content="healthchecks, crontab monitoring, python health check, bash health check, cron monitoring, cron tutorial, cron howto, api health check, open source">
{% endblock %}


{% block docs_content %}

<h2>How {% site_name %} Works</h2>
<p>
Each check in <a href="{% url 'hc-index' %}">My Checks</a>
page has a unique "ping" URL. Whenever you make a HTTP request to this URL,
{% site_name %} records the request and updates the "Last Ping" value of
the corresponding check.
</p>

<p>When a certain, configurable amount of time passes since last received ping,
the check is considered "late". {% site_name %} then
waits for additional time (configured with the "Grace Time" parameter) and,
if still no ping, sends you an alert.</p>

<p>As long as the monitored service sends pings on time, you receive no
alerts. As soon as it fails to check in on time, you get notified.
It is a simple idea.</p>

<h2 class="rule">Signalling a Success</h2>

<p>
    At the end of your batch job, add a bit of code to request
    your ping URL.
</p>
<ul>
    <li>HTTP and HTTPS protocols both work.
        Prefer HTTPS, but on old systems you may need to fall back to HTTP.</li>
    <li>Request method can be GET, POST or HEAD</li>
    <li>Both IPv4 and IPv6 work</li>
    <li>
        For HTTP POST requests, you can include additional diagnostic information
        for your own reference in the request body. If the request body looks
        like a UTF-8 string, {% site_name %} will log the first 10 kilobytes
        of the request body, so you can inspect it later.
    </li>
</ul>

<p>The response will have status code "200 OK" and response body will be a
short and simple string "OK".</p>

<a name="fail-event"></a>
<h2 class="rule">Signalling a Failure</h2>
<p>
    Append <code>/fail</code> to a ping URL and use it to actively signal a
    failure. Requesting the <code>/fail</code> URL will immediately mark the
    check as "down". You can use this feature to minimize the delay from
    your monitored service failing to you getting a notification.
</p>
<p>Below is a skeleton code example in Python which signals a failure when the
work function returns an unexpected value or throws an exception:</p>

{% include "front/snippets/python_requests_fail.html" %}

<a name="start-event"></a>
<h2 class="rule">Measuring Job Execution Time</h2>
<p>
    Append <code>/start</code> to a ping URL and use it to signal
    when a job starts. After receiving a start signal, {% site_name %}
    will show the check as "Started". It will store the "start" events and
    display the job execution times. The job execution times are calculated as the time
    gaps between adjacent "start" and "complete" events.
</p>
<p>
    Signalling a start kicks off a separate timer: the job
    now <strong>must</strong> signal a success within its configured
    "Grace Time", or it will get marked as "down".
</p>

<p>Below is a code example in Python:</p>

{% include "front/snippets/python_requests_start.html" %}

<h2 class="rule">Examples</h2>

<p>
    Jump to example:
    <a href="#crontab">Crontab</a>,
    <a href="#bash">Bash</a>,
    <a href="#python">Python</a>,
    <a href="#ruby">Ruby</a>,
    <a href="#node">Node</a>,
    <a href="#php">PHP</a>,
    <a href="#cs">C#</a>,
    <a href="#browser">Browser</a>,
    <a href="#powershell">PowerShell</a>,
    <a href="#email">Email</a>.
</p>

<a name="crontab"></a>
<h3 class="docs-example">Crontab</h3>

<p>
When using cron, probably the easiest is to append a curl
or wget call after your command. The scheduled time comes,
and your command runs. If it completes successfully (exit code 0),
curl or wget runs a HTTP GET call to the ping URL.
</p>

{% include "front/snippets/crontab.html" %}

<p>With this simple modification, you monitor several failure
scenarios:</p>

<ul>
    <li>The whole machine has stopped working (power outage, janitor stumbles on wires, VPS provider problems, etc.) </li>
    <li>cron daemon is not running, or has invalid configuration</li>
    <li>cron does start your task, but the task exits with non-zero exit code</li>
</ul>

<p>Either way, when your task doesn't finish successfully, you will soon
know about it.</p>

<p>The extra options to curl are meant to suppress any output, unless it hits
an error. This is to prevent cron from sending an email every time the
task runs. Feel free to adjust the curl options to your liking.
</p>
<table class="table curl-opts">
    <tr>
        <th>&amp;&amp;</th>
        <td>Run curl only if <code>/home/user/backup.sh</code> succeeds</td>
    </tr>
    <tr>
        <th>
            -f,  --fail
        </th>
        <td>Makes curl treat non-200 responses as errors</td>
    </tr>
    <tr>
        <th>-s, --silent</th>
        <td>Silent or quiet mode. Don't show progress meter or error messages.</td>
    </tr>
    <tr>
        <th>-S, --show-error</th>
        <td>When used with -s it makes curl show error message if it fails.</td>
    </tr>
    <tr>
        <th>--retry &lt;num&gt;</th>
        <td>
            If a transient error is returned when curl tries to perform a
            transfer, it will retry this number of times before  giving  up.
            Setting  the number  to  0  makes curl do no retries
            (which is the default). Transient error means either: a timeout,
            an FTP 4xx response code or an HTTP 5xx response code.
        </td>
    </tr>
    <tr>
        <th>&gt; /dev/null</th>
        <td>
            Redirect curl's stdout to /dev/null (error messages go to stderr,)
        </td>
    </tr>
</table>

<a name="bash"></a>
<h3 class="docs-example">Bash or a shell script</h3>

<p>Both <code>curl</code> and <code>wget</code> examples accomplish the same
thing: they fire off a HTTP GET method.</p>

<p>
    If using <code>curl</code>, make sure it is installed on your target system.
    Ubuntu, for example, does not have curl installed out of the box.
</p>

{% include "front/snippets/bash_curl.html" %}
{% include "front/snippets/bash_wget.html" %}

<a name="python"></a>
<h3 class="docs-example">Python</h3>

<p>
    If you are already using the
    <a href="http://docs.python-requests.org/en/master/">requests</a> library,
    it's convenient to also use it here:
</p>
{% include "front/snippets/python_requests.html" %}

<p>
    Otherwise, you can use the <code>urllib</code> standard module.
</p>

{% include "front/snippets/python_urllib2.html" %}

<p>
    You can include additional diagnostic information in the
    in the request body (for POST requests), or in the  "User-Agent"
    request header:
</p>

{% include "front/snippets/python_requests_payload.html" %}

<a name="ruby"></a>
<h3 class="docs-example">Ruby</h3>
{% include "front/snippets/ruby.html" %}

<a name="node"></a>
<h3 class="docs-example">Node</h3>
{% include "front/snippets/node.html" %}

<a name="php"></a>
<h3 class="docs-example">PHP</h3>
{% include "front/snippets/php.html" %}

<a name="cs"></a>
<h3 class="docs-example">C#</h3>
{% include "front/snippets/cs.html" %}

<a name="browser"></a>
<h3>Browser</h3>
<p>
    {% site_name %} includes <code>Access-Control-Allow-Origin:*</code>
    CORS header in its ping responses, so cross-domain AJAX requests
    should work.
</p>
{% include "front/snippets/browser.html" %}

<a name="powershell"></a>
<h3 class="docs-example">PowerShell</h3>
<p>
    You can use <a href="https://msdn.microsoft.com/en-us/powershell/mt173057.aspx">PowerShell</a>
    and Windows Task Scheduler to automate various tasks on a Windows system.
    From within a PowerShell script it is also easy to ping {% site_name %}.
</p>
<p>Here is a simple PowerShell script that pings {% site_name %}.
When scheduled to run with Task Scheduler, it will essentially
just send regular "I'm alive" messages. You can of course extend it to
do more things.</p>

{% include "front/snippets/powershell.html" %}

<p>Save the above to e.g. <code>C:\Scripts\healthchecks.ps1</code>. Then use
the following command in a Scheduled Task to run the script:
</p>

<div class="highlight">
    <pre>powershell.exe -ExecutionPolicy bypass -File C:\Scripts\healthchecks.ps1</pre>
</div>

<p>In simple cases, you can also pass the script to PowerShell directly,
using the "-command" argument:</p>

{% include "front/snippets/powershell_inline.html" %}

<a name="email"></a>
<h3 class="docs-example">Email</h3>
<p>
    As an alternative to HTTP/HTTPS requests,
    you can "ping" this check by sending an
    email message to <strong>{{ ping_email }}</strong>
</p>
<p>
    This is useful for end-to-end testing weekly email delivery.
</p>
<p>
    An example scenario: you have a cron job which runs weekly and
    sends weekly email reports to a list of e-mail addresses. You have already
    set up a check to get alerted when your cron job fails to run.
    But what you ultimately want to check is your emails <em>get sent and
    get delivered</em>.
</p>
<p>
    The solution: set up another check, and add its
    @{{ ping_email_domain }} address to your list of recipient email addresses.
    Set its Period to 1 week. As long as your weekly email script runs
    correctly, the check will be regularly pinged and will stay up.
</p>


<h2 class="rule">When Alerts Are Sent</h2>
<p>
    Each check has a configurable <strong>Period</strong> parameter, with the default value of one day.
    For periodic tasks, this is the expected time gap between two runs.
</p>
<p>
    Additionally, each check has a <strong>Grace</strong> parameter, with default value of one hour.
    You can use this parameter to account for run time variance of tasks.
    For example, if a backup task completes in 50 seconds one day, and
    completes in 60 seconds the following day, you might not want to get
    alerted because the backups are 10 seconds late.
</p>
<p>Each check can be in one of the following states:</p>

<table class="table">
    <tr>
        <td>
            <span class="status icon-new"></span>
        </td>
        <td>
            <strong>New.</strong>
            A check that has been created, but has not received any pings yet.
        </td>
    </tr>
    <tr>
        <td>
            <span class="status icon-paused"></span>
        </td>
        <td>
            <strong>Monitoring Paused.</strong>
            You can resume monitoring of a paused check by pinging it.
        </td>
    </tr>
    <tr>
        <td>
            <span class="status icon-started"></span>
        </td>
        <td>
            <strong>Started.</strong>
            The check has received a "start" signal, and is currently running.
        </td>
    </tr>
    <tr>
        <td>
            <span class="status icon-up"></span>
        </td>
        <td>
            <strong>Up.</strong>
            Time since last ping has not exceeded <strong>Period</strong>.
        </td>
    </tr>
    <tr>
        <td>
            <span class="status icon-grace"></span>
        </td>
        <td>
            <strong>Late.</strong>
            Time since last ping has exceeded <strong>Period</strong>,
            but has not yet exceeded <strong>Period</strong> + <strong>Grace</strong>.
        </td>
    </tr>
    <tr>
        <td>
            <span class="status icon-down"></span>
        </td>
        <td>
            <p><strong>Down.</strong> The check has not received a "success"
                ping in time, or it has received an explicit "fail" signal.
            </p>
            <p>
            When a check goes into the "Down" state, {% site_name %}
            sends you an alert.
            </p>
        </td>
    </tr>
</table>

{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/clipboard.min.js' %}"></script>
<script src="{% static 'js/snippet-copy.js' %}"></script>
{% endcompress %}
{% endblock %}

healthdemo/templates/front/log_status_text.html
{% load humanize %}
{% with check.get_status as status %}
    {% if status == "down" %}
        This check is down. Last ping was {{ check.last_ping|naturaltime }}.
    {% elif status == "up" %}
        This check is up. Last ping was {{ check.last_ping|naturaltime }}.
    {% elif status == "grace" %}
        This check is late. Last ping was {{ check.last_ping|naturaltime }}.
    {% elif status == "paused" %}
        This check is paused.
    {% elif status == "new" %}
        This check has never received a ping.
    {% elif status == "started" %}
        This check is currently running. Started {{ check.last_start|naturaltime }}.
    {% endif %}
{% endwith %}

healthdemo/templates/front/projects.html
{% extends "base.html" %}
{% load compress static hc_extras %}

{% block title %}{% site_name %}{% endblock %}


{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1 class="settings-title">
            My Projects
        </h1>

        <div id="project-selector" class="row">
            {% for project in projects %}
            <a href="{% url 'hc-checks' project.code %}">
                <div class="col-sm-6 col-md-4">
                    <div class="panel project {% if project == request.profile.current_project %}selected{% endif %}">
                        <div class="status icon-{{ project.overall_status }}"></div>

                        <h4>{{ project }}</h4>

                        <div>
                            {% with project.check_set.count as n %}
                            {{ n }} check{{ n|pluralize }},
                            {% endwith %}

                            {% with project.channel_set.count as n %}
                            {{ n }} integration{{ n|pluralize }}
                            {% endwith %}
                        </div>
                        <div class="text-muted">
                            {{ project.owner.email }}
                        </div>

                    </div>
                </div>
            </a>
            {% endfor %}

            <a id="add-project" href="#" data-toggle="modal" data-target="#add-project-modal">
                <div class="col-sm-6 col-md-4">
                    <div class="panel project {% if project == request.profile.current_project %}selected{% endif %}">
                        New Project&hellip;
                    </div>
                </div>
            </a>

        </div>
    </div>
</div>

{% include "accounts/add_project_modal.html" %}

{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/project.js' %}"></script>
{% endcompress %}
{% endblock %}

healthdemo/templates/front/unsubscribe_success.html
{% extends "base_bare.html" %}
{% load hc_extras %}

{% block title %}Unsubscribed{% endblock %}

{% block content %}
<h1>Unsubscribed</h1>
<p>
    Your email address has been unsubscribed from
    {% site_name %} notifications.
</p>
{% endblock %}